# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AggieDish' do
  pod 'GoogleSignIn'
  pod 'gRPC-Swift'
  pod 'gRPC-Swift-Plugins'
  pod 'SwiftProtobuf'
  pod 'ExytePopupView'
  use_frameworks!
end
